### ISSUE TITLE
addVars not working for spatial output of climr downscale 

### ISSUE THREAD

**Issue by cour10eygrace** [bcgov/SS_quantSppFeas#14]
if select out_spatial=TRUE on downscale call in climr, addVars function will not work because input is not a dataframe. How to fix this? @kdaust @cmahony

**Comment by cmahony** [comment]
@cour10eygrace i recommend you work with out_spatial=FALSE.

**Comment by cour10eygrace** [comment]
workaround with rasterize from vector then pull info out to data frame and addvars
